# Generated by Django 5.2.4 on 2025-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
